import Head from 'next/head';
import CustomDatePicker from './CustomDatePicker';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
          <h4 className={styles.title}>Select a Date</h4>
          <CustomDatePicker />
        </div>
        <div className={styles.grid}>
        </div>
      </main>
    </>
  );
}
